name: gcm-filters_docs
dependencies:
  - python=3.8
  - numpy
  - scipy
  - xarray
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - ipython
  - nbconvert
  - nbformat
  - ipykernel # not strictly necessary but this is nice to run notebooks in this env to test
  - pandoc
  - pip
  - pip:
    - docrep<=0.2.7
    - nbsphinx
    - jupyter_client
    - sphinx_pangeo_theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
